//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Livro { get; set; }
        public string Autor { get; set; }
        public string Editora { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Paginas { get; set; }
        public Nullable<int> Estoque { get; set; }
    }
}
